spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: 
    password: 
    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
